version: '3.8'

services:
  app:
    build: .
    ports:
      - "8002:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27018
      - REDIS_URL=redis://redis:6379
      - DATABASE_NAME=book_borrowing
      - JWT_SECRET_KEY=ScalableAs123!
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - AUTH_SERVICE_URL=http://localhost:3000
      - CATALOG_SERVICE_URL=http://localhost:8000
      - SERVICE_NAME=borrowing_service
      - ENVIRONMENT=development
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./app:/code/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:7.0
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    command: mongod --port 27018
    healthcheck:
      test: mongosh --port 27018 --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data: